#!/bin/sh

DL_UA="Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Ubuntu/10.04 Chromium/7.0.517.44 Chrome/7.0.517.44 Safari/534.7" 
DL_FILE=brandibelle_$(echo "$1" | awk 'BEGIN { FS="[/.]" } { print $9 }').flv
DL_URL=$(curl "http://www.brandibelle.com/t4/pps=comein/trailers/jb1743-mushroom-tip.html" | grep -e "http.*mp4" | awk 'BEGIN { FS="'"'"'" } { print $2 }')

wget -c  -U "$DL_UA" "$DL_URL" -O "$DL_FILE"


