#!/bin/sh


DL_UA="Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Ubuntu/10.04 Chromium/7.0.517.44 Chrome/7.0.517.44 Safari/534.7" 
DL_REFERER=""
DL_FILE=narutoget_$(echo $1 | cut -d"/" -f5).flv
DL_URL=$(curl -A "$DL_UA" "$1" | grep -e "fbcdn.*swf" | head -n1 | awk 'BEGIN { FS="video_src=" } { print $2 }' | awk 'BEGIN { FS="&amp;" } { print $1 }')
echo Downloading \"$DL_URL\" to \"$DL_FILE\"
#curl -A "$DL_UA" -e "$DL_REFERER" -C - "$DL_URL" > $DL_FILE
wget -c --referer="$DL_REFERER" -U "$DL_UA" "$DL_URL" -O "$DL_FILE"
