#!/bin/sh

DL_UA="Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Ubuntu/10.04 Chromium/7.0.517.44 Chrome/7.0.517.44 Safari/534.7" 
DL_REFERER="http://cdn1.static.spankwire.com/Controls/UserControls/Players/v3/swf/flvPlayer.swf"
DL_FILE=spankwire_$(echo "$1" | cut -d"/" -f5).flv
DL_URL_A=$(curl "$1" | grep -e "videoPath=" | head -n1 | sed 's/.*videoPath=\(.*\)".*/\1/')
DL_URL=$(curl "$1"/"$DL_URL_A" | grep -e "http.*" | sed 's/.*<url>\(http.*\)<\/url>.*/\1/' | sed 's/&amp;/\&/g')

wget -c --referer="$DL_REFERER" -U "$DL_UA" "$DL_URL" -O "$DL_FILE"

