#!/bin/sh


DL_UA="Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Ubuntu/10.04 Chromium/7.0.517.44 Chrome/7.0.517.44 Safari/534.7" 
DL_REFERER=""

DL_FILE=$(echo $1 | sed -e 's/.*v=\(.*\)$/\1/g')


DL_URL=$(curl -A "$DL_UA" "$1" | grep videoplayback | tail -n1 | 
awk 'BEGIN { FS="fmt_stream_map" } { print $2 }' | 
cut -d'"' -f3 | tr "," "\n" | tr "|" "\n" | sed -e 's/\\\//\//g' | 
while read a; do echo $a | 
sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | 
xargs echo -e; done | grep http |
head -n1)


DL_EXT=$(curl "$DL_URL" -I -L | grep -e "^Content-Type" | cut -d":" -f2 | cut -d"/" -f2 | sed -e 's/\(x-\)*\(.*\)/\2/g')

curl "$DL_URL" -L > "$DL_FILE.$DL_EXT"

#curl "$DL_URL" -I -L | grep "Content-Length" | cut -d":" -f2
#while read a; do
#	x=$(curl "$a" -I -L | grep "Content-Length" | cut -d":" -f2)
#	echo $a $x
#done 


	
#DL_URL="$DL_URLA?start=0&id=player&client=FLASH%20LNX%2010,1,102,65&version=4.1.60"
#echo Downloading \"$DL_URL\" to \"$DL_FILE\"
#curl -A "$DL_UA" -e "$DL_REFERER" -C - "$DL_URL" > $DL_FILE
#wget -c --referer="$DL_REFERER" -U "$DL_UA" "$DL_URL" -O "$DL_FILE"
