#!/bin/sh


DL_UA="Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Ubuntu/10.04 Chromium/7.0.517.44 Chrome/7.0.517.44 Safari/534.7" 
DL_REFERER=""

DL_FILE=$(echo $1 | sed -e 's/.*v=\(.*\)$/\1/g')


DL_URL=$(curl -A "$DL_UA" "$1" | grep videoplayback | tail -n1 | 
awk 'BEGIN { FS="fmt_stream_map" } { print $2 }' | 
cut -d'"' -f3 | tr "," "\n" | tr "|" "\n" | sed -e 's/\\\//\//g' | 
while read a; do echo $a | 
sed -e's/%\([0-9A-F][0-9A-F]\)/\\\\\x\1/g' | 
xargs echo -e; done | grep http |
head -n1)


DL_EXT=$(curl "$DL_URL" -I -L | grep -e "^Content-Type" | tail -n1 | cut -d":" -f2 | cut -d"/" -f2 | sed -e 's/\(x-\)*\(.*\)[\r\n]/\2/g')

wget -c "$DL_URL" -L -O "$DL_FILE.$DL_EXT"

#wget -c --referer="$DL_REFERER" -U "$DL_UA" "$DL_URL" -O "$DL_FILE"
